# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from collections.abc import AsyncIterator
import json
from typing import Any, Callable, Iterable, Mapping

import httpx
from fastapi import HTTPException, Request
from fastapi.responses import Response, StreamingResponse

from .config import settings

# Strip transport state, client credentials, and headers that could make a
# caller override Cofer One IA's internal routing. Everything else is treated
# as protocol metadata and forwarded (Codex x-codex-*, Anthropic beta/version,
# OpenAI beta/session headers, SDK telemetry headers, etc.).
_HOP_BY_HOP_HEADERS = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    "host",
    "content-length",
}
_CLIENT_CREDENTIAL_HEADERS = {
    "authorization",
    "x-api-key",
    "api-key",
    "cookie",
    "chatgpt-account-id",
}
_ROUTING_OVERRIDE_HEADERS = {
    "x-headroom-base-url",
    "x-litellm-api-key",
}
_RESPONSE_BLOCK_HEADERS = _HOP_BY_HOP_HEADERS | {"set-cookie", "content-length"}


def filter_request_headers(headers: Iterable[tuple[str, str]]) -> dict[str, str]:
    result: dict[str, str] = {}
    for key, value in headers:
        lowered = key.lower()
        if lowered in _HOP_BY_HOP_HEADERS:
            continue
        if lowered in _CLIENT_CREDENTIAL_HEADERS:
            continue
        if lowered in _ROUTING_OVERRIDE_HEADERS or lowered.startswith("x-headroom-"):
            continue
        result[key] = value
    return result


def upstream_headers(
    request: Request | None = None,
    *,
    include_internal_auth: bool = True,
    extra_headers: Mapping[str, str] | None = None,
) -> dict[str, str]:
    headers = filter_request_headers(request.headers.items()) if request is not None else {}
    if include_internal_auth and settings.litellm_master_key:
        headers["Authorization"] = f"Bearer {settings.litellm_master_key}"
    if extra_headers:
        # These headers are generated by Cofer One IA after all caller-supplied
        # routing overrides have been stripped. This lets the gateway safely
        # steer trusted internal proxies such as Headroom without exposing a
        # client-controlled routing primitive.
        headers.update(extra_headers)
    return headers


def response_headers(headers: httpx.Headers) -> dict[str, str]:
    return {
        key: value
        for key, value in headers.items()
        if key.lower() not in _RESPONSE_BLOCK_HEADERS
    }


def _upstream_url(request: Request, path: str, base_url: str | None = None) -> str:
    url = f"{(base_url or settings.headroom_url).rstrip('/')}{path}"
    if request.url.query:
        url = f"{url}?{request.url.query}"
    return url


async def proxy_json_request(
    request: Request,
    path: str,
    *,
    stream: bool | None = None,
    model_rewriter: Callable[[str], str] | None = None,
    payload_transformer: Callable[[dict[str, Any]], dict[str, Any]] | None = None,
    upstream_base_url: str | None = None,
    include_internal_auth: bool = True,
    extra_upstream_headers: Mapping[str, str] | None = None,
) -> Response:
    body = await request.body()
    payload = None
    try:
        parsed = await request.json()
        if isinstance(parsed, dict):
            payload = parsed
    except Exception:
        payload = None

    payload_changed = False
    if payload is not None and payload_transformer is not None:
        transformed = payload_transformer(dict(payload))
        if not isinstance(transformed, dict):
            raise HTTPException(status_code=500, detail="Invalid internal payload transformation")
        payload = transformed
        payload_changed = True

    if payload is not None and model_rewriter is not None:
        model = payload.get("model")
        if isinstance(model, str):
            rewritten_model = model_rewriter(model)
            if rewritten_model != model:
                payload = dict(payload)
                payload["model"] = rewritten_model
                payload_changed = True

    if payload is not None and payload_changed:
        body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")

    if stream is None:
        stream = bool(payload.get("stream", False)) if payload is not None else False

    url = _upstream_url(request, path, upstream_base_url)
    if not stream:
        try:
            async with httpx.AsyncClient(timeout=settings.request_timeout_seconds) as client:
                response = await client.request(
                    request.method,
                    url,
                    content=body,
                    headers=upstream_headers(
                        request,
                        include_internal_auth=include_internal_auth,
                        extra_headers=extra_upstream_headers,
                    ),
                )
        except httpx.HTTPError as exc:
            raise HTTPException(status_code=502, detail=f"Upstream unavailable: {exc}") from exc
        return Response(
            content=response.content,
            status_code=response.status_code,
            headers=response_headers(response.headers),
        )

    client = httpx.AsyncClient(timeout=settings.request_timeout_seconds)
    try:
        upstream_request = client.build_request(
            request.method,
            url,
            content=body,
            headers=upstream_headers(
                request,
                include_internal_auth=include_internal_auth,
                extra_headers=extra_upstream_headers,
            ),
        )
        response = await client.send(upstream_request, stream=True)
    except httpx.HTTPError as exc:
        await client.aclose()
        raise HTTPException(status_code=502, detail=f"Upstream unavailable: {exc}") from exc

    if not response.is_success:
        content = await response.aread()
        status = response.status_code
        headers = response_headers(response.headers)
        await response.aclose()
        await client.aclose()
        return Response(content=content, status_code=status, headers=headers)

    async def iterator() -> AsyncIterator[bytes]:
        try:
            async for chunk in response.aiter_raw():
                yield chunk
        finally:
            await response.aclose()
            await client.aclose()

    return StreamingResponse(
        iterator(),
        status_code=response.status_code,
        headers=response_headers(response.headers),
    )
