# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from collections.abc import AsyncIterator
import json
from typing import Any, Callable, Iterable, Mapping

import httpx
from fastapi import HTTPException, Request
from fastapi.responses import Response, StreamingResponse

from .config import settings

# Strip transport state, client credentials, headers that could make a caller
# override Cofer One IA's internal routing, and Anthropic beta negotiation that
# is not portable to the non-Anthropic providers behind the gateway.
_HOP_BY_HOP_HEADERS = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    "host",
    "content-length",
}
_CLIENT_CREDENTIAL_HEADERS = {
    "authorization",
    "x-api-key",
    "api-key",
    "cookie",
    "chatgpt-account-id",
}
_ROUTING_OVERRIDE_HEADERS = {
    "x-headroom-base-url",
    "x-litellm-api-key",
}
_UNSUPPORTED_PROTOCOL_HEADERS = {
    "anthropic-beta",
}
_RESPONSE_BLOCK_HEADERS = _HOP_BY_HOP_HEADERS | {"set-cookie", "content-length"}
_ANTHROPIC_PATHS = {"/v1/messages", "/v1/messages/count_tokens"}


def filter_request_headers(headers: Iterable[tuple[str, str]]) -> dict[str, str]:
    result: dict[str, str] = {}
    for key, value in headers:
        lowered = key.lower()
        if lowered in _HOP_BY_HOP_HEADERS:
            continue
        if lowered in _CLIENT_CREDENTIAL_HEADERS:
            continue
        if lowered in _ROUTING_OVERRIDE_HEADERS or lowered.startswith("x-headroom-"):
            continue
        if lowered in _UNSUPPORTED_PROTOCOL_HEADERS:
            continue
        result[key] = value
    return result


def upstream_headers(
    request: Request | None = None,
    *,
    include_internal_auth: bool = True,
    extra_headers: Mapping[str, str] | None = None,
) -> dict[str, str]:
    headers = filter_request_headers(request.headers.items()) if request is not None else {}
    if include_internal_auth and settings.litellm_master_key:
        headers["Authorization"] = f"Bearer {settings.litellm_master_key}"
    if extra_headers:
        # These headers are generated by Cofer One IA after all caller-supplied
        # routing overrides have been stripped. This lets the gateway safely
        # steer trusted internal proxies such as Headroom without exposing a
        # client-controlled routing primitive.
        headers.update(extra_headers)
    return headers


def response_headers(headers: httpx.Headers) -> dict[str, str]:
    return {
        key: value
        for key, value in headers.items()
        if key.lower() not in _RESPONSE_BLOCK_HEADERS
    }


def _upstream_url(request: Request, path: str, base_url: str | None = None) -> str:
    url = f"{(base_url or settings.headroom_url).rstrip('/')}{path}"
    if request.url.query:
        url = f"{url}?{request.url.query}"
    return url


def _anthropic_payload_requires_direct_litellm(payload: dict[str, Any] | None) -> bool:
    """Return true when Headroom must not touch Anthropic beta/tool-search payloads."""
    if not isinstance(payload, dict):
        return False
    tools = payload.get("tools")
    if not isinstance(tools, list):
        return False
    for tool in tools:
        if not isinstance(tool, dict):
            continue
        tool_type = tool.get("type")
        if isinstance(tool_type, str) and tool_type.startswith("tool_search_tool_"):
            return True
        if tool.get("defer_loading") is not None:
            return True
    return False


def _anthropic_error_type(status_code: int) -> str:
    if status_code in {400, 422}:
        return "invalid_request_error"
    if status_code == 401:
        return "authentication_error"
    if status_code == 402:
        return "billing_error"
    if status_code == 403:
        return "permission_error"
    if status_code == 404:
        return "not_found_error"
    if status_code == 413:
        return "request_too_large"
    if status_code == 429:
        return "rate_limit_error"
    if status_code == 529:
        return "overloaded_error"
    return "api_error"


def _anthropic_error_message(content: bytes, status_code: int) -> str:
    text = content.decode("utf-8", errors="replace").strip()
    if not text:
        return f"Upstream request failed with HTTP {status_code}"
    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return text
    if isinstance(payload, dict):
        error = payload.get("error")
        if isinstance(error, dict):
            message = error.get("message")
            if isinstance(message, str) and message.strip():
                return message.strip()
        if isinstance(error, str) and error.strip():
            return error.strip()
        detail = payload.get("detail")
        if isinstance(detail, str) and detail.strip():
            return detail.strip()
    return text


def _anthropic_error_response(
    *,
    status_code: int,
    content: bytes,
    headers: httpx.Headers,
) -> Response:
    outgoing_headers = response_headers(headers)
    outgoing_headers = {
        key: value
        for key, value in outgoing_headers.items()
        if key.lower() != "content-type"
    }
    body = {
        "type": "error",
        "error": {
            "type": _anthropic_error_type(status_code),
            "message": _anthropic_error_message(content, status_code),
        },
    }
    return Response(
        content=json.dumps(body, ensure_ascii=False, separators=(",", ":")),
        status_code=status_code,
        headers=outgoing_headers,
        media_type="application/json",
    )


def _is_chatgpt_anthropic_request(original_payload: dict[str, Any] | None) -> bool:
    if not isinstance(original_payload, dict):
        return False
    model = original_payload.get("model")
    return isinstance(model, str) and model.startswith("openai/")


async def proxy_json_request(
    request: Request,
    path: str,
    *,
    stream: bool | None = None,
    model_rewriter: Callable[[str], str] | None = None,
    payload_transformer: Callable[[dict[str, Any]], dict[str, Any]] | None = None,
    upstream_base_url: str | None = None,
    include_internal_auth: bool = True,
    extra_upstream_headers: Mapping[str, str] | None = None,
) -> Response:
    body = await request.body()
    payload = None
    try:
        parsed = await request.json()
        if isinstance(parsed, dict):
            payload = parsed
    except Exception:
        payload = None
    original_payload = dict(payload) if isinstance(payload, dict) else None

    payload_changed = False
    if payload is not None and payload_transformer is not None:
        transformed = payload_transformer(dict(payload))
        if not isinstance(transformed, dict):
            raise HTTPException(status_code=500, detail="Invalid internal payload transformation")
        payload = transformed
        payload_changed = True

    if payload is not None and model_rewriter is not None:
        model = payload.get("model")
        if isinstance(model, str):
            rewritten_model = model_rewriter(model)
            if rewritten_model != model:
                payload = dict(payload)
                payload["model"] = rewritten_model
                payload_changed = True

    if payload is not None and payload_changed:
        body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")

    if stream is None:
        stream = bool(payload.get("stream", False)) if payload is not None else False

    selected_base_url = upstream_base_url
    selected_extra_headers = extra_upstream_headers
    if path == "/v1/messages":
        configured_base = (selected_base_url or settings.headroom_url).rstrip("/")
        headroom_base = settings.headroom_url.rstrip("/")
        has_beta_header = "anthropic-beta" in {key.lower() for key in request.headers.keys()}
        if configured_base == headroom_base and (
            has_beta_header or _anthropic_payload_requires_direct_litellm(original_payload)
        ):
            # ToolSearch/deferred-tool requests must not pass through another
            # semantic proxy after Cofer has normalized them. Route the already
            # rewritten Anthropic-compatible deployment directly to LiteLLM.
            selected_base_url = settings.litellm_url
            selected_extra_headers = None

    url = _upstream_url(request, path, selected_base_url)
    if not stream:
        try:
            async with httpx.AsyncClient(timeout=settings.request_timeout_seconds) as client:
                response = await client.request(
                    request.method,
                    url,
                    content=body,
                    headers=upstream_headers(
                        request,
                        include_internal_auth=include_internal_auth,
                        extra_headers=selected_extra_headers,
                    ),
                )
        except httpx.HTTPError as exc:
            raise HTTPException(status_code=502, detail=f"Upstream unavailable: {exc}") from exc
        if (
            not response.is_success
            and path in _ANTHROPIC_PATHS
            and _is_chatgpt_anthropic_request(original_payload)
        ):
            return _anthropic_error_response(
                status_code=response.status_code,
                content=response.content,
                headers=response.headers,
            )
        return Response(
            content=response.content,
            status_code=response.status_code,
            headers=response_headers(response.headers),
        )

    client = httpx.AsyncClient(timeout=settings.request_timeout_seconds)
    try:
        upstream_request = client.build_request(
            request.method,
            url,
            content=body,
            headers=upstream_headers(
                request,
                include_internal_auth=include_internal_auth,
                extra_headers=selected_extra_headers,
            ),
        )
        response = await client.send(upstream_request, stream=True)
    except httpx.HTTPError as exc:
        await client.aclose()
        raise HTTPException(status_code=502, detail=f"Upstream unavailable: {exc}") from exc

    if not response.is_success:
        content = await response.aread()
        status = response.status_code
        headers = response.headers
        await response.aclose()
        await client.aclose()
        if path in _ANTHROPIC_PATHS and _is_chatgpt_anthropic_request(original_payload):
            return _anthropic_error_response(
                status_code=status,
                content=content,
                headers=headers,
            )
        return Response(content=content, status_code=status, headers=response_headers(headers))

    async def iterator() -> AsyncIterator[bytes]:
        try:
            async for chunk in response.aiter_raw():
                yield chunk
        finally:
            await response.aclose()
            await client.aclose()

    return StreamingResponse(
        iterator(),
        status_code=response.status_code,
        headers=response_headers(response.headers),
    )
